<?php

/**
 * @file
 * Contains loggedin_users_list.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function loggedin_users_list_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the loggedin_users_list module.
    case 'help.page.loggedin_users_list':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Showing the list of loggedin users who have currently loggedin.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function loggedin_users_list_theme() {
  return [
    'loggedin_users_list' => [
      'render element' => 'children',
    ],
  ];
}
